language: java
sudo: false

jdk:
  - openjdk8

jobs:
  include:
  - stage: compile
    script: mvn clean compile
  - stage: test
    script: mvn clean test
  - stage: package
    script: mvn clean package